ALTER TYPE "UserRole" ADD VALUE 'PLATFORM_ADMIN';
ALTER TYPE "UserRole" ADD VALUE 'MANAGER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE 'MANAGER_OPERATOR';
ALTER TYPE "UserRole" ADD VALUE 'COLLECTOR';
ALTER TYPE "UserRole" ADD VALUE 'HOUSEHOLD';
ALTER TYPE "UserRole" ADD VALUE 'BUSINESS_BUYER';
